-- pg_cte_force does not expose any SQL objects: all behavior
-- is controlled through the "pg_cte_force.mode" GUC and the
-- post_parse_analyze hook defined in _PG_init().
-- This script exists only because CREATE EXTENSION requires it.
